spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    favicon:
      enabled: true
